apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: blockchain-server-test # give any name 
spec:
 replicas: 3
 template:
   metadata:
     name: blockchain-server-test
     labels:
       run: etherprivate
   spec:
     containers:
       - name: ether
         image: "registry.ng.bluemix.net/etherprivate/myimage" # your registery name 
         imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
 name: my-service-test-11 # give a service name
 labels:
   run: etherprivate
spec:
 type: NodePort
 selector:
   run: etherprivate
 ports:
  - protocol: TCP
    port: 8545 # it shall be 8545 and no other port !!!!!
    nodePort: 30090 # Give a port to access the application publically 